dovecot_config_version = 2.4.3
dovecot_storage_version = 2.4.3

log_path = /dev/stderr
info_log_path = /dev/stdout

@mailbox_defaults = english
namespace inbox {
  inbox = yes
}

passdb passwd-file {
  passwd_file_path = /opt/users/nasmail-users
}

protocols = imap lmtp
auth_mechanisms = plain login

mail_driver = maildir
mail_home = /var/vmail/%{user}
mailbox_list_utf8 = yes
mail_utf8_extensions = yes

mail_uid = dockervmail
mail_gid = dockervmail

service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = postfix
    mode = 0660
    user = postfix
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    group = postfix
    mode = 0600
    user = postfix
  }
}
