# nasmail compose example
services:
  nasmail:
    # image: ghcr.io/jabenninghoff/nasmail:version # uncomment and use with specific version number for production
    image: nasmail:dev # use with docker-build.sh for local development, remove for production
    restart: unless-stopped
    hostname: nasmail.test
    ports:
      - "25:25" # SMTP
      - "143:143" # IMAP
      - "587:587" # Submission
      - "993:993" # IMAPS
    volumes:
      - ./tls:/opt/nasmail/tls:ro
      - ./users:/opt/nasmail/users:ro
      - ./vmail:/var/vmail
    environment:
      - MAIL_HOST=mail.nasmail.test
      - TLS_KEY=/opt/nasmail/tls/privkey.pem
      - TLS_CERT=/opt/nasmail/tls/fullchain.pem
