# nasmail compose example
services:
  nasmail:
    image: ghcr.io/jabenninghoff/nasmail:latest
    restart: unless-stopped
    ports:
      - "25:25" # SMTP
      - "143:143" # IMAP
      - "587:587" # Submission
      - "993:993" # IMAPS
    volumes:
      - ./tls:/opt/tls:ro
      - ./users:/opt/users:ro
      - ./vmail:/var/vmail
    environment:
      - MAIL_HOST=mail.nasmail.test
      - TLS_KEY=/opt/tls/privkey.pem
      - TLS_CERT=/opt/tls/fullchain.pem
